"""add embendding id column

Revision ID: b9d7e74cd0ac
Revises: 24270da903d0
Create Date: 2026-03-07 20:44:36.713687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d7e74cd0ac'
down_revision: Union[str, None] = '24270da903d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('embedding_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'embedding_id')
    # ### end Alembic commands ###
